services:
  postgres:
    image: postgres:17-bookworm
    container_name: funding_db

    environment:
      POSTGRES_DB: funding_db
      POSTGRES_USER: funding_user
      POSTGRES_PASSWORD: funding_pass

    volumes:
      - ./volumes/postgres/data:/var/lib/postgresql/data
      - ./volumes/postgres/init.sql:/docker-entrypoint-initdb.d/01-init.sql:ro

    ports:
      - "5432:5432"
    restart: unless-stopped
    shm_size: 128mb

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U funding_user -d funding_db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
