dev:
    uv run uvicorn main:app --reload

start-db:
    docker compose -f docker/compose.yaml up -d

stop-db:
    docker compose -f docker/compose.yaml down

clean:
    docker compose -f docker/compose.yaml down -v
    rm -rf docker/volumes/postgres/data

reset-db:
    just clean
    just start-db
